In [2]:
import pandas as pd

In [7]:
conn_uri = 'postgresql://itversity_retail_user:itversity@localhost:5432/itversity_retail_db'

In [8]:
pd.read_sql('orders', conn_uri)

       order_id             order_date  order_customer_id     order_status
0             1  2013-07-25 00:00:00.0              11599           CLOSED
1             2  2013-07-25 00:00:00.0                256  PENDING_PAYMENT
2             3  2013-07-25 00:00:00.0              12111         COMPLETE
3             4  2013-07-25 00:00:00.0               8827           CLOSED
4             5  2013-07-25 00:00:00.0              11318         COMPLETE
...         ...                    ...                ...              ...
68878     68879  2014-07-09 00:00:00.0                778         COMPLETE
68879     68880  2014-07-13 00:00:00.0               1117         COMPLETE
68880     68881  2014-07-19 00:00:00.0               2518  PENDING_PAYMENT
68881     68882  2014-07-22 00:00:00.0              10000          ON_HOLD
68882     68883  2014-07-23 00:00:00.0               5533         COMPLETE

[68883 rows x 4 columns]

In [10]:
query = ''' 
SELECT * FROM orders
LIMIT 10
'''

In [11]:
pd.read_sql(query, conn_uri)

   order_id             order_date  order_customer_id     order_status
0         1  2013-07-25 00:00:00.0              11599           CLOSED
1         2  2013-07-25 00:00:00.0                256  PENDING_PAYMENT
2         3  2013-07-25 00:00:00.0              12111         COMPLETE
3         4  2013-07-25 00:00:00.0               8827           CLOSED
4         5  2013-07-25 00:00:00.0              11318         COMPLETE
5         6  2013-07-25 00:00:00.0               7130         COMPLETE
6         7  2013-07-25 00:00:00.0               4530         COMPLETE
7         8  2013-07-25 00:00:00.0               2911       PROCESSING
8         9  2013-07-25 00:00:00.0               5657  PENDING_PAYMENT
9        10  2013-07-25 00:00:00.0               5648  PENDING_PAYMENT