#Overview of Pandas for Data Processing

Let us get an overview of Python Pandas Library.

- Pandas is one of the most popular libraries of Python.
- Usage: Data Processing, Data Analysis (including Visualization)
- Robust APIs to read data from different sources, process data and write data to different targets.
- Integrated with File Formats, Databases, REST APIs, etc
- Easy to integrate with additional File Systems or Databases (install additional libraries)

In [1]:
!pip install pandas

Requirement already satisfied: pandas in /opt/miniconda3/lib/python3.13/site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in /opt/miniconda3/lib/python3.13/site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/miniconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /opt/miniconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [ ]:
pd.

In [3]:
help(pd.read_csv)

Help on function read_csv in module pandas:

read_csv(
    filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]',
    *,
    sep: 'str | None | lib.NoDefault' = <no_default>,
    delimiter: 'str | None | lib.NoDefault' = None,
    header: "int | Sequence[int] | None | Literal['infer']" = 'infer',
    names: 'Sequence[Hashable] | None | lib.NoDefault' = <no_default>,
    index_col: 'IndexLabel | Literal[False] | None' = None,
    usecols: 'UsecolsArgType' = None,
    dtype: 'DtypeArg | None' = None,
    engine: 'CSVEngine | None' = None,
    converters: 'Mapping[HashableT, Callable] | None' = None,
    true_values: 'list | None' = None,
    false_values: 'list | None' = None,
    skipinitialspace: 'bool' = False,
    skiprows: 'list[int] | int | Callable[[Hashable], bool] | None' = None,
    skipfooter: 'int' = 0,
    nrows: 'int | None' = None,
    na_values: 'Hashable | Iterable[Hashable] | Mapping[Hashable, Iterable[Hashable]] | None' = None,
    keep_default_na: 'bool' = True,
    na_filter: 'bool' = True,
    skip_blank_lines: 'bool' = True,
    parse_dates: 'bool | Sequence[Hashable] | None' = None,
    date_format: 'str | dict[Hashable, str] | None' = None,
    dayfirst: 'bool' = False,
    cache_dates: 'bool' = True,
    iterator: 'bool' = False,
    chunksize: 'int | None' = None,
    compression: 'CompressionOptions' = 'infer',
    thousands: 'str | None' = None,
    decimal: 'str' = '.',
    lineterminator: 'str | None' = None,
    quotechar: 'str' = '"',
    quoting: 'int' = 0,
    doublequote: 'bool' = True,
    escapechar: 'str | None' = None,
    comment: 'str | None' = None,
    encoding: 'str | None' = None,
    encoding_errors: 'str | None' = 'strict',
    dialect: 'str | csv.Dialect | None' = None,
    on_bad_lines: 'str' = 'error',
    low_memory: 'bool' = True,
    memory_map: 'bool' = False,
    float_precision: "Literal['high', 'legacy', 'round_trip'] | None" = None,
    storage_options: 'StorageOptions | None' = None,
    dtype_backend: 'DtypeBackend | lib.NoDefault' = <no_default>
) -> 'DataFrame | TextFileReader'
    Read a comma-separated values (csv) file into DataFrame.

    Also supports optionally iterating or breaking of the file
    into chunks.

    Additional help can be found in the online docs for
    `IO Tools <https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html>`_.

    Parameters
    ----------
    filepath_or_buffer : str, path object or file-like object
        Any valid string path is acceptable. The string could be a URL. Valid
        URL schemes include http, ftp, s3, gs, and file. For file URLs, a host is
        expected. A local file could be: file://localhost/path/to/table.csv.

        If you want to pass in a path object, pandas accepts any ``os.PathLike``.

        By file-like object, we refer to objects with a ``read()`` method, such as
        a file handle (e.g. via builtin ``open`` function) or ``StringIO``.
    sep : str, default ','
        Character or regex pattern to treat as the delimiter. If ``sep=None``, the
        C engine cannot automatically detect
        the separator, but the Python parsing engine can, meaning the latter will
        be used and automatically detect the separator from only the first valid
        row of the file by Python's builtin sniffer tool, ``csv.Sniffer``.
        In addition, separators longer than 1 character and different from
        ``'\s+'`` will be interpreted as regular expressions and will also force
        the use of the Python parsing engine. Note that regex delimiters are prone
        to ignoring quoted data. Regex example: ``'\r\t'``.
    delimiter : str, optional
        Alias for ``sep``.
    header : int, Sequence of int, 'infer' or None, default 'infer'
        Row number(s) containing column labels and marking the start of the
        data (zero-indexed). Default behavior is to infer the column names:
        if no ``names``
        are passed the behavior is identical to ``header=0`` and column
        names are inferred from the first line of the file, if column
        names are passed explicitly to ``names`` then the behavior is identical to
        ``header=None``. Explicitly pass ``header=0`` to be able to
        replace existing names. The header can be a list of integers that
        specify row locations for a :class:`~pandas.MultiIndex` on the columns
        e.g. ``[0, 1, 3]``. Intervening rows that are not specified will be
        skipped (e.g. 2 in this example is skipped). Note that this
        parameter ignores commented lines and empty lines if
        ``skip_blank_lines=True``, so ``header=0`` denotes the first line of
        data rather than the first line of the file.

        When inferred from the file contents, headers are kept distinct from
        each other by renaming duplicate names with a numeric suffix of the form
        ``".{{count}}"`` starting from 1, e.g. ``"foo"`` and ``"foo.1"``.
        Empty headers are named ``"Unnamed: {{i}}"`` or ``
        "Unnamed: {{i}}_level_{{level}}"``
        in the case of MultiIndex columns.
    names : Sequence of Hashable, optional
        Sequence of column labels to apply. If the file contains a header row,
        then you should explicitly pass ``header=0`` to override the column names.
        Duplicates in this list are not allowed.
    index_col : Hashable, Sequence of Hashable or False, optional
        Column(s) to use as row label(s), denoted either by column labels or column
        indices.  If a sequence of labels or indices is given,
        :class:`~pandas.MultiIndex`
        will be formed for the row labels.

        Note: ``index_col=False`` can be used to force pandas to *not* use the first
        column as the index, e.g., when you have a malformed file with delimiters at
        the end of each line.
    usecols : Sequence of Hashable or Callable, optional
        Subset of columns to select, denoted either
        by column labels or column indices.
        If list-like, all elements must either
        be positional (i.e. integer indices into the document columns) or strings
        that correspond to column names provided either by the user in ``names`` or
        inferred from the document header row(s).
        If ``names`` are given, the document
        header row(s) are not taken into account. For example, a valid list-like
        ``usecols`` parameter would be ``[0, 1, 2]`` or ``['foo', 'bar', 'baz']``.
        Element order is ignored, so ``usecols=[0, 1]`` is the same as ``[1, 0]``.
        To instantiate a :class:`~pandas.DataFrame` from ``data`` with element order
        preserved use ``pd.read_csv(data, usecols=['foo', 'bar'])[['foo', 'bar']]``
        for columns in ``['foo', 'bar']`` order or
        ``pd.read_csv(data, usecols=['foo', 'bar'])[['bar', 'foo']]``
        for ``['bar', 'foo']`` order.

        If callable, the callable function will be evaluated against the column
        names, returning names where the callable function evaluates to ``True``. An
        example of a valid callable argument would be ``lambda x: x.upper() in
        ['AAA', 'BBB', 'DDD']``. Using this parameter results in much faster
        parsing time and lower memory usage.
    dtype : dtype or dict of {{Hashable : dtype}}, optional
        Data type(s) to apply to either the whole dataset or individual columns.
        E.g., ``{{'a': np.float64, 'b': np.int32, 'c': 'Int64'}}``
        Use ``str`` or ``object`` together with suitable ``na_values`` settings
        to preserve and not interpret ``dtype``.
        If ``converters`` are specified, they will be applied INSTEAD
        of ``dtype`` conversion. Specify a ``defaultdict`` as input where
        the default determines the ``dtype``
        of the columns which are not explicitly
        listed.
    engine : {{'c', 'python', 'pyarrow'}}, optional
        Parser engine to use. The C and pyarrow engines are faster,
        while the python engine
        is currently more feature-complete. Multithreading
        is currently only supported by
        the pyarrow engine. Some features of the "pyarrow" engine
        are unsupported or may not work correctly.
    converters : dict of {{Hashable : Callable}}, optional
        Functions for converting values in specified columns. Keys can either
        be column labels or column indices.
    true_values : list, optional
        Values to consider as ``True`` in addition
        to case-insensitive variants of 'True'.
    false_values : list, optional
        Values to consider as ``False`` in addition to case-insensitive
        variants of 'False'.
    skipinitialspace : bool, default False
        Skip spaces after delimiter.
    skiprows : int, list of int or Callable, optional
        Line numbers to skip (0-indexed) or number of lines to skip (``int``)
        at the start of the file.

        If callable, the callable function will be evaluated against the row
        indices, returning ``True`` if the row should be skipped and ``False``
        otherwise.
        An example of a valid callable argument would be ``lambda x: x in [0, 2]``.
    skipfooter : int, default 0
        Number of lines at bottom of file to skip (Unsupported with ``engine='c'``).
    nrows : int, optional
        Number of rows of file to read. Useful for reading pieces of large files.
        Refers to the number of data rows in the returned DataFrame, excluding:

        * The header row containing column names.
        * Rows before the header row, if ``header=1`` or larger.

        Example usage:

        * To read the first 999,999 (non-header) rows:
          ``read_csv(..., nrows=999999)``

        * To read rows 1,000,000 through 1,999,999:
          ``read_csv(..., skiprows=1000000, nrows=999999)``

    na_values : Hashable, Iterable of Hashable or dict of {{Hashable : Iterable}},
        optional
        Additional strings to recognize as ``NA``/``NaN``. If ``dict``
        passed, specific
        per-column ``NA`` values.  By default the following values
        are interpreted as
        ``NaN``: empty string, "NaN", "N/A", "NULL", and other common
        representations of missing data.
    keep_default_na : bool, default True
        Whether or not to include the default ``NaN`` values when parsing the data.
        Depending on whether ``na_values`` is passed in, the behavior is as follows:

        * If ``keep_default_na`` is ``True``, and ``na_values``
          are specified, ``na_values``
          is appended to the default ``NaN`` values used for parsing.
        * If ``keep_default_na`` is ``True``, and ``na_values`` are not specified, only
          the default ``NaN`` values are used for parsing.
        * If ``keep_default_na`` is ``False``, and ``na_values`` are specified, only
          the ``NaN`` values specified ``na_values`` are used for parsing.
        * If ``keep_default_na`` is ``False``, and ``na_values`` are not specified, no
          strings will be parsed as ``NaN``.

        Note that if ``na_filter`` is passed in as ``False``,
        the ``keep_default_na`` and
        ``na_values`` parameters will be ignored.
    na_filter : bool, default True
        Detect missing value markers (empty strings and the value of ``na_values``). In
        data without any ``NA`` values, passing ``na_filter=False`` can improve the
        performance of reading a large file.
    skip_blank_lines : bool, default True
        If ``True``, skip over blank lines rather than interpreting as ``NaN`` values.
    parse_dates : bool, None, list of Hashable, default None
        The behavior is as follows:

        * ``bool``. If ``True`` -> try parsing the index.
        * ``None``. Behaves like ``True`` if ``date_format`` is specified.
        * ``list`` of ``int`` or names.
          e.g. If ``[1, 2, 3]`` -> try parsing columns 1, 2, 3
          each as a separate date column.

        If a column or index cannot be represented as an array of ``datetime``,
        say because of an unparsable value or a mixture of timezones, the column
        or index will be returned unaltered as an ``object`` data type. For
        non-standard ``datetime`` parsing, use :func:`~pandas.to_datetime` after
        :func:`~pandas.read_csv`.

        Note: A fast-path exists for iso8601-formatted dates.
    date_format : str or dict of column -> format, optional
        Format to use for parsing dates and/or times when
        used in conjunction with ``parse_dates``.
        The strftime to parse time, e.g. :const:`"%d/%m/%Y"`. See
        `strftime documentation
        <https://docs.python.org/3/library/datetime.html
        #strftime-and-strptime-behavior>`_ for more information on choices, though
        note that :const:`"%f"`` will parse all the way up to nanoseconds.
        You can also pass:

        - "ISO8601", to parse any `ISO8601 <https://en.wikipedia.org/wiki/ISO_8601>`_
          time string (not necessarily in exactly the same format);
        - "mixed", to infer the format for each element individually. This is risky,
          and you should probably use it along with `dayfirst`.

        .. versionadded:: 2.0.0
    dayfirst : bool, default False
        DD/MM format dates, international and European format.
    cache_dates : bool, default True
        If ``True``, use a cache of unique, converted dates to apply the ``datetime``
        conversion. May produce significant speed-up when parsing duplicate
        date strings, especially ones with timezone offsets.

    iterator : bool, default False
        Return ``TextFileReader`` object for iteration or getting chunks with
        ``get_chunk()``.
    chunksize : int, optional
        Number of lines to read from the file per chunk. Passing a value will cause the
        function to return a ``TextFileReader`` object for iteration.
        See the `IO Tools docs
        <https://pandas.pydata.org/pandas-docs/stable/io.html#io-chunking>`_
        for more information on ``iterator`` and ``chunksize``.

    compression : str or dict, default 'infer'
        For on-the-fly decompression of on-disk data.
        If 'infer' and 'filepath_or_buffer' is
        path-like, then detect compression from the following extensions: '.gz',
        '.bz2', '.zip', '.xz', '.zst', '.tar', '.tar.gz', '.tar.xz' or '.tar.bz2'
        (otherwise no compression).
        If using 'zip' or 'tar', the ZIP file must contain only
        one data file to be read in.
        Set to ``None`` for no decompression.
        Can also be a dict with key ``'method'`` set
        to one of {``'zip'``, ``'gzip'``, ``'bz2'``,
        ``'zstd'``, ``'xz'``, ``'tar'``} and
        other key-value pairs are forwarded to
        ``zipfile.ZipFile``, ``gzip.GzipFile``,
        ``bz2.BZ2File``, ``zstandard.ZstdDecompressor``, ``lzma.LZMAFile`` or
        ``tarfile.TarFile``, respectively.
        As an example, the following could be passed for
        Zstandard decompression using a
        custom compression dictionary:
        ``compression={'method': 'zstd', 'dict_data': my_compression_dict}``.

    thousands : str (length 1), optional
        Character acting as the thousands separator in numerical values.
    decimal : str (length 1), default '.'
        Character to recognize as decimal point (e.g., use ',' for European data).
    lineterminator : str (length 1), optional
        Character used to denote a line break. Only valid with C parser.
    quotechar : str (length 1), optional
        Character used to denote the start and end of a quoted item. Quoted
        items can include the ``delimiter`` and it will be ignored.
    quoting : {{0 or csv.QUOTE_MINIMAL, 1 or csv.QUOTE_ALL,
        2 or csv.QUOTE_NONNUMERIC, 3 or csv.QUOTE_NONE}}, default csv.QUOTE_MINIMAL
        Control field quoting behavior per ``csv.QUOTE_*`` constants. Default is
        ``csv.QUOTE_MINIMAL`` (i.e., 0) which implies that
        only fields containing special
        characters are quoted (e.g., characters defined
        in ``quotechar``, ``delimiter``,
        or ``lineterminator``.
    doublequote : bool, default True
        When ``quotechar`` is specified and ``quoting`` is not ``QUOTE_NONE``, indicate
        whether or not to interpret two consecutive ``quotechar`` elements INSIDE a
        field as a single ``quotechar`` element.
    escapechar : str (length 1), optional
        Character used to escape other characters.
    comment : str (length 1), optional
        Character indicating that the remainder of line should not be parsed.
        If found at the beginning
        of a line, the line will be ignored altogether. This parameter must be a
        single character. Like empty lines (as long as ``skip_blank_lines=True``),
        fully commented lines are ignored by the parameter ``header`` but not by
        ``skiprows``. For example, if ``comment='#'``, parsing
        ``#empty\na,b,c\n1,2,3`` with ``header=0`` will result in ``'a,b,c'`` being
        treated as the header.
    encoding : str, optional, default 'utf-8'
        Encoding to use for UTF when reading/writing (ex. ``'utf-8'``). `List of Python
        standard encodings
        <https://docs.python.org/3/library/codecs.html#standard-encodings>`_ .

    encoding_errors : str, optional, default 'strict'
        How encoding errors are treated. `List of possible values
        <https://docs.python.org/3/library/codecs.html#error-handlers>`_ .

    dialect : str or csv.Dialect, optional
        If provided, this parameter will override values (default or not) for the
        following parameters: ``delimiter``, ``doublequote``, ``escapechar``,
        ``skipinitialspace``, ``quotechar``, and ``quoting``. If it is necessary to
        override values, a ``ParserWarning`` will be issued. See ``csv.Dialect``
        documentation for more details.
    on_bad_lines : {{'error', 'warn', 'skip'}} or Callable, default 'error'
        Specifies what to do upon encountering a bad line (a line with too many fields).
        Allowed values are:

        - ``'error'``, raise an Exception when a bad line is encountered.
        - ``'warn'``, raise a warning when a bad line is
          encountered and skip that line.
        - ``'skip'``, skip bad lines without raising or warning when
          they are encountered.
        - Callable, function that will process a single bad line.
            - With ``engine='python'``, function with signature
              ``(bad_line: list[str]) -> list[str] | None``.
              ``bad_line`` is a list of strings split by the ``sep``.
              If the function returns ``None``, the bad line will be ignored.
              If the function returns a new ``list`` of strings with
              more elements than
              expected, a ``ParserWarning`` will be emitted while
              dropping extra elements.
            - With ``engine='pyarrow'``, function with signature
              as described in pyarrow documentation: `invalid_row_handler
              <https://arrow.apache.org/docs/python
              /generated/pyarrow.csv.ParseOptions.html
              #pyarrow.csv.ParseOptions.invalid_row_handler>`_.

        .. versionchanged:: 2.2.0

            Callable for ``engine='pyarrow'``

    low_memory : bool, default True
        Internally process the file in chunks, resulting in lower memory use
        while parsing, but possibly mixed type inference.  To ensure no mixed
        types either set ``False``, or specify the type with the ``dtype`` parameter.
        Note that the entire file is read into a single :class:`~pandas.DataFrame`
        regardless, use the ``chunksize`` or ``iterator``
        parameter to return the data in
        chunks. (Only valid with C parser).
    memory_map : bool, default False
        If a filepath is provided for ``filepath_or_buffer``, map the file object

In [ ]:
pd.read_csv('/Users/franciscocoelho/VSCodeProjects/franciscocoelh0/Random_Scripts/data/retail_db/customers/part-00000.txt')

           1  2013-07-25 00:00:00.0  11599           CLOSED
0          2  2013-07-25 00:00:00.0    256  PENDING_PAYMENT
1          3  2013-07-25 00:00:00.0  12111         COMPLETE
2          4  2013-07-25 00:00:00.0   8827           CLOSED
3          5  2013-07-25 00:00:00.0  11318         COMPLETE
4          6  2013-07-25 00:00:00.0   7130         COMPLETE
...      ...                    ...    ...              ...
68877  68879  2014-07-09 00:00:00.0    778         COMPLETE
68878  68880  2014-07-13 00:00:00.0   1117         COMPLETE
68879  68881  2014-07-19 00:00:00.0   2518  PENDING_PAYMENT
68880  68882  2014-07-22 00:00:00.0  10000          ON_HOLD
68881  68883  2014-07-23 00:00:00.0   5533         COMPLETE

[68882 rows x 4 columns]

In [7]:
pd.read_csv('/Users/franciscocoelho/VSCodeProjects/franciscocoelh0/Random_Scripts/data/retail_db/orders/part-00000.txt', header=None)

           0                      1      2                3
0          1  2013-07-25 00:00:00.0  11599           CLOSED
1          2  2013-07-25 00:00:00.0    256  PENDING_PAYMENT
2          3  2013-07-25 00:00:00.0  12111         COMPLETE
3          4  2013-07-25 00:00:00.0   8827           CLOSED
4          5  2013-07-25 00:00:00.0  11318         COMPLETE
...      ...                    ...    ...              ...
68878  68879  2014-07-09 00:00:00.0    778         COMPLETE
68879  68880  2014-07-13 00:00:00.0   1117         COMPLETE
68880  68881  2014-07-19 00:00:00.0   2518  PENDING_PAYMENT
68881  68882  2014-07-22 00:00:00.0  10000          ON_HOLD
68882  68883  2014-07-23 00:00:00.0   5533         COMPLETE

[68883 rows x 4 columns]

In [9]:
order_columns = ['order_id', 'order_date', 'order_customer_id', 'order_status']

In [ ]:
pd.read_csv(
    '/Users/franciscocoelho/VSCodeProjects/franciscocoelh0/Random_Scripts/data/retail_db/orders/part-00000.txt',
    header=None, # No need for this as we are providing column names
    names=order_columns)

       order_id             order_date  order_customer_id     order_status
0             1  2013-07-25 00:00:00.0              11599           CLOSED
1             2  2013-07-25 00:00:00.0                256  PENDING_PAYMENT
2             3  2013-07-25 00:00:00.0              12111         COMPLETE
3             4  2013-07-25 00:00:00.0               8827           CLOSED
4             5  2013-07-25 00:00:00.0              11318         COMPLETE
...         ...                    ...                ...              ...
68878     68879  2014-07-09 00:00:00.0                778         COMPLETE
68879     68880  2014-07-13 00:00:00.0               1117         COMPLETE
68880     68881  2014-07-19 00:00:00.0               2518  PENDING_PAYMENT
68881     68882  2014-07-22 00:00:00.0              10000          ON_HOLD
68882     68883  2014-07-23 00:00:00.0               5533         COMPLETE

[68883 rows x 4 columns]

In [13]:
orders = pd.read_csv(
    '/Users/franciscocoelho/VSCodeProjects/franciscocoelh0/Random_Scripts/data/retail_db/orders/part-00000.txt', 
    names=order_columns)

In [14]:
orders.columns

Index(['order_id', 'order_date', 'order_customer_id', 'order_status'], dtype='str')

In [15]:
help(orders.query)

Help on method query in module pandas.core.frame:

query(
    expr: 'str',
    *,
    parser: "Literal['pandas', 'python']" = 'pandas',
    engine: "Literal['python', 'numexpr'] | None" = None,
    local_dict: 'dict[str, Any] | None' = None,
    global_dict: 'dict[str, Any] | None' = None,
    resolvers: 'list[Mapping] | None' = None,
    level: 'int' = 0,
    inplace: 'bool' = False
) -> 'DataFrame | None' method of pandas.DataFrame instance
    Query the columns of a DataFrame with a boolean expression.

    .. warning::

        This method can run arbitrary code which can make you vulnerable to code
        injection if you pass user input to this function.

    Parameters
    ----------
    expr : str
        The query string to evaluate.

        See the documentation for :func:`eval` for details of
        supported operations and functions in the query string.

        See the documentation for :meth:`DataFrame.eval` for details on
        referring to column names and variables in the query string.
    parser : {'pandas', 'python'}, default 'pandas'
        The parser to use to construct the syntax tree from the expression. The
        default of ``'pandas'`` parses code slightly different than standard
        Python. Alternatively, you can parse an expression using the
        ``'python'`` parser to retain strict Python semantics.  See the
        :ref:`enhancing performance <enhancingperf.eval>` documentation for
        more details.
    engine : {'python', 'numexpr'}, default 'numexpr'

        The engine used to evaluate the expression. Supported engines are

        - None : tries to use ``numexpr``, falls back to ``python``
        - ``'numexpr'`` : This default engine evaluates pandas objects using
          numexpr for large speed ups in complex expressions with large frames.
        - ``'python'`` : Performs operations as if you had ``eval``'d in top
          level python. This engine is generally not that useful.

        More backends may be available in the future.
    local_dict : dict or None, optional
        A dictionary of local variables, taken from locals() by default.
    global_dict : dict or None, optional
        A dictionary of global variables, taken from globals() by default.
    resolvers : list of dict-like or None, optional
        A list of objects implementing the ``__getitem__`` special method that
        you can use to inject an additional collection of namespaces to use for
        variable lookup. For example, this is used in the
        :meth:`~DataFrame.query` method to inject the
        ``DataFrame.index`` and ``DataFrame.columns``
        variables that refer to their respective :class:`~pandas.DataFrame`
        instance attributes.
    level : int, optional
        The number of prior stack frames to traverse and add to the current
        scope. Most users will **not** need to change this parameter.
    inplace : bool
        Whether to modify the DataFrame rather than creating a new one.

    Returns
    -------
    DataFrame or None
        DataFrame resulting from the provided query expression or
        None if ``inplace=True``.

    See Also
    --------
    eval : Evaluate a string describing operations on
        DataFrame columns.
    DataFrame.eval : Evaluate a string describing operations on
        DataFrame columns.

    Notes
    -----
    The result of the evaluation of this expression is first passed to
    :attr:`DataFrame.loc` and if that fails because of a
    multidimensional key (e.g., a DataFrame) then the result will be passed
    to :meth:`DataFrame.__getitem__`.

    This method uses the top-level :func:`eval` function to
    evaluate the passed query.

    The :meth:`~pandas.DataFrame.query` method uses a slightly
    modified Python syntax by default. For example, the ``&`` and ``|``
    (bitwise) operators have the precedence of their boolean cousins,
    :keyword:`and` and :keyword:`or`. This *is* syntactically valid Python,
    however the semantics are different.

    You can change the semantics of the expression by passing the keyword
    argument ``parser='python'``. This enforces the same semantics as
    evaluation in Python space. Likewise, you can pass ``engine='python'``
    to evaluate an expression using Python itself as a backend. This is not
    recommended as it is inefficient compared to using ``numexpr`` as the
    engine.

    The :attr:`DataFrame.index` and
    :attr:`DataFrame.columns` attributes of the
    :class:`~pandas.DataFrame` instance are placed in the query namespace
    by default, which allows you to treat both the index and columns of the
    frame as a column in the frame.
    The identifier ``index`` is used for the frame index; you can also
    use the name of the index to identify it in a query. Please note that
    Python keywords may not be used as identifiers.

    For further details and examples see the ``query`` documentation in
    :ref:`indexing <indexing.query>`.

    *Backtick quoted variables*

    Backtick quoted variables are parsed as literal Python code and
    are converted internally to a Python valid identifier.
    This can lead to the following problems.

    During parsing a number of disallowed characters inside the backtick
    quoted string are replaced by strings that are allowed as a Python identifier.
    These characters include all operators in Python, the space character, the
    question mark, the exclamation mark, the dollar sign, and the euro sign.

    A backtick can be escaped by double backticks.

    See also the `Python documentation about lexical analysis
    <https://docs.python.org/3/reference/lexical_analysis.html>`__
    in combination with the source code in :mod:`pandas.core.computation.parsing`.

    Examples
    --------
    >>> df = pd.DataFrame(
    ...     {"A": range(1, 6), "B": range(10, 0, -2), "C&C": range(10, 5, -1)}
    ... )
    >>> df
       A   B  C&C
    0  1  10   10
    1  2   8    9
    2  3   6    8
    3  4   4    7
    4  5   2    6
    >>> df.query("A > B")
       A  B  C&C
    4  5  2    6

    The previous expression is equivalent to

    >>> df[df.A > df.B]
       A  B  C&C
    4  5  2    6

    For columns with spaces in their name, you can use backtick quoting.

    >>> df.query("B == `C&C`")
       A   B  C&C
    0  1  10   10

    The previous expression is equivalent to

    >>> df[df.B == df["C&C"]]
       A   B  C&C
    0  1  10   10

    Using local variable:

    >>> local_var = 2
    >>> df.query("A <= @local_var")
    A   B  C&C
    0  1  10   10
    1  2   8    9

In [17]:
orders['order_status']

0                 CLOSED
1        PENDING_PAYMENT
2               COMPLETE
3                 CLOSED
4               COMPLETE
              ...
68878           COMPLETE
68879           COMPLETE
68880    PENDING_PAYMENT
68881            ON_HOLD
68882           COMPLETE
Name: order_status, Length: 68883, dtype: str

In [18]:
orders['order_status'].unique()

<StringArray>
[         'CLOSED', 'PENDING_PAYMENT',        'COMPLETE',      'PROCESSING',
  'PAYMENT_REVIEW',         'PENDING',         'ON_HOLD',        'CANCELED',
 'SUSPECTED_FRAUD']
Length: 9, dtype: str

In [16]:
orders.query('order_status == "COMPLETE"')

       order_id             order_date  order_customer_id order_status
2             3  2013-07-25 00:00:00.0              12111     COMPLETE
4             5  2013-07-25 00:00:00.0              11318     COMPLETE
5             6  2013-07-25 00:00:00.0               7130     COMPLETE
6             7  2013-07-25 00:00:00.0               4530     COMPLETE
14           15  2013-07-25 00:00:00.0               2568     COMPLETE
...         ...                    ...                ...          ...
68875     68876  2014-07-06 00:00:00.0               4124     COMPLETE
68877     68878  2014-07-08 00:00:00.0               6753     COMPLETE
68878     68879  2014-07-09 00:00:00.0                778     COMPLETE
68879     68880  2014-07-13 00:00:00.0               1117     COMPLETE
68882     68883  2014-07-23 00:00:00.0               5533     COMPLETE

[22899 rows x 4 columns]

In [23]:
round(orders.describe())

       order_id  order_customer_id
count   68883.0            68883.0
mean    34442.0             6217.0
std     19885.0             3586.0
min         1.0                1.0
25%     17222.0             3122.0
50%     34442.0             6199.0
75%     51662.0             9326.0
max     68883.0            12435.0

In [25]:
orders.query('order_status == "COMPLETE" and order_date == "2014-01-01 00:00:00.0"')

       order_id             order_date  order_customer_id order_status
25881     25882  2014-01-01 00:00:00.0               4598     COMPLETE
25887     25888  2014-01-01 00:00:00.0               6735     COMPLETE
25888     25889  2014-01-01 00:00:00.0              10045     COMPLETE
25894     25895  2014-01-01 00:00:00.0               1044     COMPLETE
25896     25897  2014-01-01 00:00:00.0               6405     COMPLETE
25897     25898  2014-01-01 00:00:00.0               3950     COMPLETE
25900     25901  2014-01-01 00:00:00.0               3099     COMPLETE
25901     25902  2014-01-01 00:00:00.0               6083     COMPLETE
25906     25907  2014-01-01 00:00:00.0               3603     COMPLETE
25912     25913  2014-01-01 00:00:00.0               9382     COMPLETE
25913     25914  2014-01-01 00:00:00.0               9288     COMPLETE
25914     25915  2014-01-01 00:00:00.0               2963     COMPLETE
25915     25916  2014-01-01 00:00:00.0               3219     COMPLETE
25917     25918  2014-01-01 00:00:00.0                279     COMPLETE
25918     25919  2014-01-01 00:00:00.0               3052     COMPLETE
25919     25920  2014-01-01 00:00:00.0              12232     COMPLETE
25920     25921  2014-01-01 00:00:00.0              12373     COMPLETE
25921     25922  2014-01-01 00:00:00.0                224     COMPLETE
25923     25924  2014-01-01 00:00:00.0               3826     COMPLETE
25925     25926  2014-01-01 00:00:00.0              10468     COMPLETE
25926     25927  2014-01-01 00:00:00.0              10278     COMPLETE
25932     25933  2014-01-01 00:00:00.0                859     COMPLETE
25933     25934  2014-01-01 00:00:00.0               4567     COMPLETE
25935     25936  2014-01-01 00:00:00.0               3057     COMPLETE
25938     25939  2014-01-01 00:00:00.0               8989     COMPLETE
25939     25940  2014-01-01 00:00:00.0               7812     COMPLETE
25947     25948  2014-01-01 00:00:00.0               3800     COMPLETE
25949     25950  2014-01-01 00:00:00.0               6954     COMPLETE
25954     25955  2014-01-01 00:00:00.0               4962     COMPLETE
25957     25958  2014-01-01 00:00:00.0              11124     COMPLETE
25958     25959  2014-01-01 00:00:00.0               3128     COMPLETE
25959     25960  2014-01-01 00:00:00.0               7918     COMPLETE
25961     25962  2014-01-01 00:00:00.0               5170     COMPLETE
25968     25969  2014-01-01 00:00:00.0               2144     COMPLETE
25969     25970  2014-01-01 00:00:00.0                387     COMPLETE
25977     25978  2014-01-01 00:00:00.0              11726     COMPLETE
25979     25980  2014-01-01 00:00:00.0                363     COMPLETE
25980     25981  2014-01-01 00:00:00.0               8500     COMPLETE
25983     25984  2014-01-01 00:00:00.0               5961     COMPLETE
25984     25985  2014-01-01 00:00:00.0               3727     COMPLETE
61897     61898  2014-01-01 00:00:00.0              10152     COMPLETE
61903     61904  2014-01-01 00:00:00.0                470     COMPLETE
61906     61907  2014-01-01 00:00:00.0              11258     COMPLETE
61907     61908  2014-01-01 00:00:00.0               5031     COMPLETE
61909     61910  2014-01-01 00:00:00.0              11201     COMPLETE
61912     61913  2014-01-01 00:00:00.0              12218     COMPLETE
61913     61914  2014-01-01 00:00:00.0               2956     COMPLETE

In [26]:
orders.query('order_status == "COMPLETE" or order_status == "CLOSED"')

       order_id             order_date  order_customer_id order_status
0             1  2013-07-25 00:00:00.0              11599       CLOSED
2             3  2013-07-25 00:00:00.0              12111     COMPLETE
3             4  2013-07-25 00:00:00.0               8827       CLOSED
4             5  2013-07-25 00:00:00.0              11318     COMPLETE
5             6  2013-07-25 00:00:00.0               7130     COMPLETE
...         ...                    ...                ...          ...
68875     68876  2014-07-06 00:00:00.0               4124     COMPLETE
68877     68878  2014-07-08 00:00:00.0               6753     COMPLETE
68878     68879  2014-07-09 00:00:00.0                778     COMPLETE
68879     68880  2014-07-13 00:00:00.0               1117     COMPLETE
68882     68883  2014-07-23 00:00:00.0               5533     COMPLETE

[30455 rows x 4 columns]

In [27]:
orders.query('order_status == ("COMPLETE", "CLOSED")')

       order_id             order_date  order_customer_id order_status
0             1  2013-07-25 00:00:00.0              11599       CLOSED
2             3  2013-07-25 00:00:00.0              12111     COMPLETE
3             4  2013-07-25 00:00:00.0               8827       CLOSED
4             5  2013-07-25 00:00:00.0              11318     COMPLETE
5             6  2013-07-25 00:00:00.0               7130     COMPLETE
...         ...                    ...                ...          ...
68875     68876  2014-07-06 00:00:00.0               4124     COMPLETE
68877     68878  2014-07-08 00:00:00.0               6753     COMPLETE
68878     68879  2014-07-09 00:00:00.0                778     COMPLETE
68879     68880  2014-07-13 00:00:00.0               1117     COMPLETE
68882     68883  2014-07-23 00:00:00.0               5533     COMPLETE

[30455 rows x 4 columns]

In [28]:
orders['order_status'].value_counts()

order_status
COMPLETE           22899
PENDING_PAYMENT    15030
PROCESSING          8275
PENDING             7610
CLOSED              7556
ON_HOLD             3798
SUSPECTED_FRAUD     1558
CANCELED            1428
PAYMENT_REVIEW       729
Name: count, dtype: int64

In [30]:
orders.groupby('order_status')

In [31]:
type(orders.groupby('order_status'))

pandas.api.typing.DataFrameGroupBy

In [29]:
orders.groupby('order_status').count()

                 order_id  order_date  order_customer_id
order_status
CANCELED             1428        1428               1428
CLOSED               7556        7556               7556
COMPLETE            22899       22899              22899
ON_HOLD              3798        3798               3798
PAYMENT_REVIEW        729         729                729
PENDING              7610        7610               7610
PENDING_PAYMENT     15030       15030              15030
PROCESSING           8275        8275               8275
SUSPECTED_FRAUD      1558        1558               1558

In [32]:
orders.groupby('order_status').agg('count')

                 order_id  order_date  order_customer_id
order_status
CANCELED             1428        1428               1428
CLOSED               7556        7556               7556
COMPLETE            22899       22899              22899
ON_HOLD              3798        3798               3798
PAYMENT_REVIEW        729         729                729
PENDING              7610        7610               7610
PENDING_PAYMENT     15030       15030              15030
PROCESSING           8275        8275               8275
SUSPECTED_FRAUD      1558        1558               1558

In [34]:
orders.groupby('order_status')['order_id'].agg('count')

order_status
CANCELED            1428
CLOSED              7556
COMPLETE           22899
ON_HOLD             3798
PAYMENT_REVIEW       729
PENDING             7610
PENDING_PAYMENT    15030
PROCESSING          8275
SUSPECTED_FRAUD     1558
Name: order_id, dtype: int64

In [35]:
orders.groupby('order_status')['order_id'].agg(order_status ='count')

                 order_status
order_status
CANCELED                 1428
CLOSED                   7556
COMPLETE                22899
ON_HOLD                  3798
PAYMENT_REVIEW            729
PENDING                  7610
PENDING_PAYMENT         15030
PROCESSING               8275
SUSPECTED_FRAUD          1558

Getting order_month from order_date is a row level transformation

In [36]:
orders['order_month'] = orders['order_date'].str.slice(5, 7)

In [ ]:
orders.head()

,order_id,order_date,order_customer_id,order_status,order_month
0,1,2013-07-25 00:00:00.0,11599,CLOSED,07
1,2,2013-07-25 00:00:00.0,256,PENDING_PAYMENT,07
2,3,2013-07-25 00:00:00.0,12111,COMPLETE,07
3,4,2013-07-25 00:00:00.0,8827,CLOSED,07
4,5,2013-07-25 00:00:00.0,11318,COMPLETE,07

In [39]:
orders['order_year'] = orders['order_date'].str.slice(0, 4)

In [40]:
orders['order_day'] = orders['order_date'].str.slice(8, 10)

In [ ]:
orders.head()

,order_id,order_date,order_customer_id,order_status,order_month,order_year,order_day
0,1,2013-07-25 00:00:00.0,11599,CLOSED,07,2013,25
1,2,2013-07-25 00:00:00.0,256,PENDING_PAYMENT,07,2013,25
2,3,2013-07-25 00:00:00.0,12111,COMPLETE,07,2013,25
3,4,2013-07-25 00:00:00.0,8827,CLOSED,07,2013,25
4,5,2013-07-25 00:00:00.0,11318,COMPLETE,07,2013,25

In [ ]:
orders['order_lambda_month'] = orders.apply(lambda order: order.order_date[0:7], axis=1) # axis=1 means that the function is applied to each row

In [43]:
orders.head()

,order_id,order_date,order_customer_id,order_status,order_month,order_year,order_day,order_lambda_month
0,1,2013-07-25 00:00:00.0,11599,CLOSED,07,2013,25,2013-07
1,2,2013-07-25 00:00:00.0,256,PENDING_PAYMENT,07,2013,25,2013-07
2,3,2013-07-25 00:00:00.0,12111,COMPLETE,07,2013,25,2013-07
3,4,2013-07-25 00:00:00.0,8827,CLOSED,07,2013,25,2013-07
4,5,2013-07-25 00:00:00.0,11318,COMPLETE,07,2013,25,2013-07

In [ ]:
orders.groupby('order_lambda_month', 'order_status')['order_id'].agg(order_status ='count')

NameError: name 'order' is not defined

It failed because the content within the groupby is not a list.

In [48]:
orders. \
    groupby(['order_lambda_month', 'order_status'])['order_id'] \
    .agg(order_status ='count')

                                    order_status
order_lambda_month order_status
2013-07            CANCELED                   22
                   CLOSED                    161
                   COMPLETE                  515
                   ON_HOLD                    81
                   PAYMENT_REVIEW             19
...                                          ...
2014-07            PAYMENT_REVIEW             54
                   PENDING                   517
                   PENDING_PAYMENT           979
                   PROCESSING                561
                   SUSPECTED_FRAUD           101

[117 rows x 1 columns]

In [50]:
orders. \
    groupby(['order_lambda_month', 'order_status'])['order_id'] \
    .agg(order_count ='count'). \
    reset_index()

    order_lambda_month     order_status  order_count
0              2013-07         CANCELED           22
1              2013-07           CLOSED          161
2              2013-07         COMPLETE          515
3              2013-07          ON_HOLD           81
4              2013-07   PAYMENT_REVIEW           19
..                 ...              ...          ...
112            2014-07   PAYMENT_REVIEW           54
113            2014-07          PENDING          517
114            2014-07  PENDING_PAYMENT          979
115            2014-07       PROCESSING          561
116            2014-07  SUSPECTED_FRAUD          101

[117 rows x 3 columns]

# Joining Data in Pandas Dataframes

Here are the steps involved in joining data using Pandas Dataframe APIs.

 - First, we need to define index for both the dataframes that are supposed to be joined.
 - Use join to join the Dataframes based on index. The default join is left, we need to make sure right join is used based on the requirement.
 
In our case, we will join orders and customers using inner join.

In [2]:
import json

In [3]:
import pandas as pd

The json document has multiple items their values are JSON arrays.

In [41]:
def get_column_names(schemas, table_name, sorting_key='column_position'):
    column_details = schemas[table_name]
    ## return column_details
    columns = sorted(column_details, key=lambda col: col[sorting_key])
    ##return columns
    return [col['column_name'] for col in columns]

In [42]:
schemas = json.load(open('/Users/franciscocoelho/VSCodeProjects/franciscocoelh0/Random_Scripts/data/retail_db/schemas.json'))

In [6]:
order_columns = get_column_names(schemas, 'orders')

In [7]:
order_columns

['order_id', 'order_date', 'order_customer_id', 'order_status']

In [43]:
orders = pd.read_csv(
    '/Users/franciscocoelho/VSCodeProjects/franciscocoelh0/Random_Scripts/data/retail_db/orders/part-00000.txt', 
    names = order_columns)

In [44]:
customer_columns = get_column_names(schemas, 'customers')

In [10]:
customer_columns = get_column_names(schemas, 'customers')

In [11]:
customer_columns

['customer_id',
 'customer_fname',
 'customer_lname',
 'customer_email',
 'customer_password',
 'customer_street',
 'customer_city',
 'customer_state',
 'customer_zipcode']

In [45]:
customers = pd.read_csv(
    '/Users/franciscocoelho/VSCodeProjects/franciscocoelh0/Random_Scripts/data/retail_db/customers/part-00000', 
    names = customer_columns)

In [46]:
orders

       order_id             order_date  order_customer_id     order_status
0             1  2013-07-25 00:00:00.0              11599           CLOSED
1             2  2013-07-25 00:00:00.0                256  PENDING_PAYMENT
2             3  2013-07-25 00:00:00.0              12111         COMPLETE
3             4  2013-07-25 00:00:00.0               8827           CLOSED
4             5  2013-07-25 00:00:00.0              11318         COMPLETE
...         ...                    ...                ...              ...
68878     68879  2014-07-09 00:00:00.0                778         COMPLETE
68879     68880  2014-07-13 00:00:00.0               1117         COMPLETE
68880     68881  2014-07-19 00:00:00.0               2518  PENDING_PAYMENT
68881     68882  2014-07-22 00:00:00.0              10000          ON_HOLD
68882     68883  2014-07-23 00:00:00.0               5533         COMPLETE

[68883 rows x 4 columns]

In [47]:
customers

,customer_id,customer_fname,customer_lname,customer_email,customer_password,customer_street,customer_city,customer_state,customer_zipcode
0,1,Richard,Hernandez,XXXXXXXXX,XXXXXXXXX,6303 Heather Plaza,Brownsville,TX,78521
1,2,Mary,Barrett,XXXXXXXXX,XXXXXXXXX,9526 Noble Embers Ridge,Littleton,CO,80126
2,3,Ann,Smith,XXXXXXXXX,XXXXXXXXX,3422 Blue Pioneer Bend,Caguas,PR,725
3,4,Mary,Jones,XXXXXXXXX,XXXXXXXXX,8324 Little Common,San Marcos,CA,92069
4,5,Robert,Hudson,XXXXXXXXX,XXXXXXXXX,10 Crystal River Mall,Caguas,PR,725
...,...,...,...,...,...,...,...,...,...
12430,12431,Mary,Rios,XXXXXXXXX,XXXXXXXXX,1221 Cinder Pines,Kaneohe,HI,96744
12431,12432,Angela,Smith,XXXXXXXXX,XXXXXXXXX,1525 Jagged Barn Highlands,Caguas,PR,725
12432,12433,Benjamin,Garcia,XXXXXXXXX,XXXXXXXXX,5459 Noble Brook Landing,Levittown,NY,11756
12433,12434,Mary,Mills,XXXXXXXXX,XXXXXXXXX,9720 Colonial Parade,Caguas,PR,725
12434,12435,Laura,Horton,XXXXXXXXX,XXXXXXXXX,5736 Honey Downs,Summerville,SC,29483

In [ ]:
help(customers.join)

Help on method join in module pandas.core.frame:

join(
    other: 'DataFrame | Series | Iterable[DataFrame | Series]',
    on: 'IndexLabel | None' = None,
    how: 'MergeHow' = 'left',
    lsuffix: 'str' = '',
    rsuffix: 'str' = '',
    sort: 'bool' = False,
    validate: 'JoinValidate | None' = None
) -> 'DataFrame' method of pandas.DataFrame instance
    Join columns of another DataFrame.

    Join columns with `other` DataFrame either on index or on a key
    column. Efficiently join multiple DataFrame objects by index at once by
    passing a list.

    Parameters
    ----------
    other : DataFrame, Series, or a list containing any combination of them
        Index should be similar to one of the columns in this one. If a
        Series is passed, its name attribute must be set, and that will be
        used as the column name in the resulting joined DataFrame.
    on : str, list of str, or array-like, optional
        Column or index level name(s) in the caller to join on the index
        in `other`, otherwise joins index-on-index. If multiple
        values given, the `other` DataFrame must have a MultiIndex. Can
        pass an array as the join key if it is not already contained in
        the calling DataFrame. Like an Excel VLOOKUP operation.
    how : {'left', 'right', 'outer', 'inner', 'cross', 'left_anti', 'right_anti'},
        default 'left'
        How to handle the operation of the two objects.

        * left: use calling frame's index (or column if on is specified)
        * right: use `other`'s index.
        * outer: form union of calling frame's index (or column if on is
          specified) with `other`'s index, and sort it lexicographically.
        * inner: form intersection of calling frame's index (or column if
          on is specified) with `other`'s index, preserving the order
          of the calling's one.
        * cross: creates the cartesian product from both frames, preserves the order
          of the left keys.
        * left_anti: use set difference of calling frame's index and `other`'s
          index.
        * right_anti: use set difference of `other`'s index and calling frame's
          index.
    lsuffix : str, default ''
        Suffix to use from left frame's overlapping columns.
    rsuffix : str, default ''
        Suffix to use from right frame's overlapping columns.
    sort : bool, default False
        Order result DataFrame lexicographically by the join key. If False,
        the order of the join key depends on the join type (how keyword).
    validate : str, optional
        If specified, checks if join is of specified type.

        * "one_to_one" or "1:1": check if join keys are unique in both left
          and right datasets.
        * "one_to_many" or "1:m": check if join keys are unique in left dataset.
        * "many_to_one" or "m:1": check if join keys are unique in right dataset.
        * "many_to_many" or "m:m": allowed, but does not result in checks.

    Returns
    -------
    DataFrame
        A dataframe containing columns from both the caller and `other`.

    See Also
    --------
    DataFrame.merge : For column(s)-on-column(s) operations.

    Notes
    -----
    Parameters `on`, `lsuffix`, and `rsuffix` are not supported when
    passing a list of `DataFrame` objects.

    Examples
    --------
    >>> df = pd.DataFrame(
    ...     {
    ...         "key": ["K0", "K1", "K2", "K3", "K4", "K5"],
    ...         "A": ["A0", "A1", "A2", "A3", "A4", "A5"],
    ...     }
    ... )

    >>> df
      key   A
    0  K0  A0
    1  K1  A1
    2  K2  A2
    3  K3  A3
    4  K4  A4
    5  K5  A5

    >>> other = pd.DataFrame({"key": ["K0", "K1", "K2"], "B": ["B0", "B1", "B2"]})

    >>> other
      key   B
    0  K0  B0
    1  K1  B1
    2  K2  B2

    Join DataFrames using their indexes.

    >>> df.join(other, lsuffix="_caller", rsuffix="_other")
      key_caller   A key_other    B
    0         K0  A0        K0   B0
    1         K1  A1        K1   B1
    2         K2  A2        K2   B2
    3         K3  A3       NaN  NaN
    4         K4  A4       NaN  NaN
    5         K5  A5       NaN  NaN

    If we want to join using the key columns, we need to set key to be
    the index in both `df` and `other`. The joined DataFrame will have
    key as its index.

    >>> df.set_index("key").join(other.set_index("key"))
          A    B
    key
    K0   A0   B0
    K1   A1   B1
    K2   A2   B2
    K3   A3  NaN
    K4   A4  NaN
    K5   A5  NaN

    Another option to join using the key columns is to use the `on`
    parameter. DataFrame.join always uses `other`'s index but we can use
    any column in `df`. This method preserves the original DataFrame's
    index in the result.

    >>> df.join(other.set_index("key"), on="key")
      key   A    B
    0  K0  A0   B0
    1  K1  A1   B1
    2  K2  A2   B2
    3  K3  A3  NaN
    4  K4  A4  NaN
    5  K5  A5  NaN

    Using non-unique key values shows how they are matched.

    >>> df = pd.DataFrame(
    ...     {
    ...         "key": ["K0", "K1", "K1", "K3", "K0", "K1"],
    ...         "A": ["A0", "A1", "A2", "A3", "A4", "A5"],
    ...     }
    ... )

    >>> df
      key   A
    0  K0  A0
    1  K1  A1
    2  K1  A2
    3  K3  A3
    4  K0  A4
    5  K1  A5

    >>> df.join(other.set_index("key"), on="key", validate="m:1")
      key   A    B
    0  K0  A0   B0
    1  K1  A1   B1
    2  K1  A2   B1
    3  K3  A3  NaN
    4  K0  A4   B0
    5  K1  A5   B1

In [48]:
customers.set_index('customer_id')

,customer_fname,customer_lname,customer_email,customer_password,customer_street,customer_city,customer_state,customer_zipcode
customer_id,,,,,,,,
1,Richard,Hernandez,XXXXXXXXX,XXXXXXXXX,6303 Heather Plaza,Brownsville,TX,78521
2,Mary,Barrett,XXXXXXXXX,XXXXXXXXX,9526 Noble Embers Ridge,Littleton,CO,80126
3,Ann,Smith,XXXXXXXXX,XXXXXXXXX,3422 Blue Pioneer Bend,Caguas,PR,725
4,Mary,Jones,XXXXXXXXX,XXXXXXXXX,8324 Little Common,San Marcos,CA,92069
5,Robert,Hudson,XXXXXXXXX,XXXXXXXXX,10 Crystal River Mall,Caguas,PR,725
...,...,...,...,...,...,...,...,...
12431,Mary,Rios,XXXXXXXXX,XXXXXXXXX,1221 Cinder Pines,Kaneohe,HI,96744
12432,Angela,Smith,XXXXXXXXX,XXXXXXXXX,1525 Jagged Barn Highlands,Caguas,PR,725
12433,Benjamin,Garcia,XXXXXXXXX,XXXXXXXXX,5459 Noble Brook Landing,Levittown,NY,11756
12434,Mary,Mills,XXXXXXXXX,XXXXXXXXX,9720 Colonial Parade,Caguas,PR,725
12435,Laura,Horton,XXXXXXXXX,XXXXXXXXX,5736 Honey Downs,Summerville,SC,29483

In [49]:
customers = customers.set_index('customer_id')

In [50]:
order = orders.set_index('order_customer_id')

In [51]:
customer_orders = customers. \
join(order, how='inner')

In [52]:
customer_orders

,customer_fname,customer_lname,customer_email,customer_password,customer_street,customer_city,customer_state,customer_zipcode,order_id,order_date,order_status
customer_id,,,,,,,,,,,
1,Richard,Hernandez,XXXXXXXXX,XXXXXXXXX,6303 Heather Plaza,Brownsville,TX,78521,22945,2013-12-13 00:00:00.0,COMPLETE
2,Mary,Barrett,XXXXXXXXX,XXXXXXXXX,9526 Noble Embers Ridge,Littleton,CO,80126,15192,2013-10-29 00:00:00.0,PENDING_PAYMENT
2,Mary,Barrett,XXXXXXXXX,XXXXXXXXX,9526 Noble Embers Ridge,Littleton,CO,80126,33865,2014-02-18 00:00:00.0,COMPLETE
2,Mary,Barrett,XXXXXXXXX,XXXXXXXXX,9526 Noble Embers Ridge,Littleton,CO,80126,57963,2013-08-02 00:00:00.0,ON_HOLD
2,Mary,Barrett,XXXXXXXXX,XXXXXXXXX,9526 Noble Embers Ridge,Littleton,CO,80126,67863,2013-11-30 00:00:00.0,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...
12434,Mary,Mills,XXXXXXXXX,XXXXXXXXX,9720 Colonial Parade,Caguas,PR,725,42915,2014-04-16 00:00:00.0,COMPLETE
12434,Mary,Mills,XXXXXXXXX,XXXXXXXXX,9720 Colonial Parade,Caguas,PR,725,51800,2014-06-14 00:00:00.0,ON_HOLD
12434,Mary,Mills,XXXXXXXXX,XXXXXXXXX,9720 Colonial Parade,Caguas,PR,725,61777,2013-12-26 00:00:00.0,COMPLETE
12435,Laura,Horton,XXXXXXXXX,XXXXXXXXX,5736 Honey Downs,Summerville,SC,29483,41643,2014-04-08 00:00:00.0,PENDING
12435,Laura,Horton,XXXXXXXXX,XXXXXXXXX,5736 Honey Downs,Summerville,SC,29483,61629,2013-12-21 00:00:00.0,CANCELED

In [53]:
customer_orders.shape

(68883, 11)

In [35]:
customer_test = customers. \
join(order,
     on='customer_id'
     ,how='left')

In [36]:
customer_test

,customer_fname,customer_lname,customer_email,customer_password,customer_street,customer_city,customer_state,customer_zipcode,order_id,order_date,order_status
customer_id,,,,,,,,,,,
1,Richard,Hernandez,XXXXXXXXX,XXXXXXXXX,6303 Heather Plaza,Brownsville,TX,78521,22945.0,2013-12-13 00:00:00.0,COMPLETE
2,Mary,Barrett,XXXXXXXXX,XXXXXXXXX,9526 Noble Embers Ridge,Littleton,CO,80126,15192.0,2013-10-29 00:00:00.0,PENDING_PAYMENT
2,Mary,Barrett,XXXXXXXXX,XXXXXXXXX,9526 Noble Embers Ridge,Littleton,CO,80126,33865.0,2014-02-18 00:00:00.0,COMPLETE
2,Mary,Barrett,XXXXXXXXX,XXXXXXXXX,9526 Noble Embers Ridge,Littleton,CO,80126,57963.0,2013-08-02 00:00:00.0,ON_HOLD
2,Mary,Barrett,XXXXXXXXX,XXXXXXXXX,9526 Noble Embers Ridge,Littleton,CO,80126,67863.0,2013-11-30 00:00:00.0,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...
12434,Mary,Mills,XXXXXXXXX,XXXXXXXXX,9720 Colonial Parade,Caguas,PR,725,42915.0,2014-04-16 00:00:00.0,COMPLETE
12434,Mary,Mills,XXXXXXXXX,XXXXXXXXX,9720 Colonial Parade,Caguas,PR,725,51800.0,2014-06-14 00:00:00.0,ON_HOLD
12434,Mary,Mills,XXXXXXXXX,XXXXXXXXX,9720 Colonial Parade,Caguas,PR,725,61777.0,2013-12-26 00:00:00.0,COMPLETE
12435,Laura,Horton,XXXXXXXXX,XXXXXXXXX,5736 Honey Downs,Summerville,SC,29483,41643.0,2014-04-08 00:00:00.0,PENDING
12435,Laura,Horton,XXXXXXXXX,XXXXXXXXX,5736 Honey Downs,Summerville,SC,29483,61629.0,2013-12-21 00:00:00.0,CANCELED

In [57]:
customer_orders. \
    reset_index(names='customer_id'). \
    groupby('customer_id')['customer_id']. \
    agg('count')

customer_id
1         1
2         4
3         7
4         6
5         4
         ..
12431    16
12432    10
12433     4
12434     8
12435     2
Name: customer_id, Length: 12405, dtype: int64

In [ ]:
customer_orders. \
    reset_index(names='customer_id'). \
    groupby('customer_id')['customer_id']. \
    agg(order_count='count'). \
    reset_index(). \
    query('order_count >= 10')

       customer_id  order_count
70              71           10
171            172           10
173            174           12
196            197           11
219            221           15
...            ...          ...
12311        12341           10
12317        12347           10
12375        12406           10
12400        12431           16
12401        12432           10

[699 rows x 2 columns]

In [62]:
help(orders.sort_values)

Help on method sort_values in module pandas.core.frame:

sort_values(
    by: 'IndexLabel',
    *,
    axis: 'Axis' = 0,
    ascending: 'bool | list[bool] | tuple[bool, ...]' = True,
    inplace: 'bool' = False,
    kind: 'SortKind' = 'quicksort',
    na_position: 'str' = 'last',
    ignore_index: 'bool' = False,
    key: 'ValueKeyFunc | None' = None
) -> 'DataFrame | None' method of pandas.DataFrame instance
    Sort by the values along either axis.

    Parameters
    ----------
    by : str or list of str
        Name or list of names to sort by.

        - if `axis` is 0 or `'index'` then `by` may contain index
          levels and/or column labels.
        - if `axis` is 1 or `'columns'` then `by` may contain column
          levels and/or index labels.
    axis : "{0 or 'index', 1 or 'columns'}", default 0
         Axis to be sorted.
    ascending : bool or list of bool, default True
         Sort ascending vs. descending. Specify list for multiple sort
         orders.  If this is a list of bools, must match the length of
         the by.
    inplace : bool, default False
         If True, perform operation in-place.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, default 'quicksort'
         Choice of sorting algorithm. See also :func:`numpy.sort` for more
         information. `mergesort` and `stable` are the only stable algorithms. For
         DataFrames, this option is only applied when sorting on a single
         column or label.
    na_position : {'first', 'last'}, default 'last'
         Puts NaNs at the beginning if `first`; `last` puts NaNs at the
         end.
    ignore_index : bool, default False
         If True, the resulting axis will be labeled 0, 1, …, n - 1.
    key : callable, optional
        Apply the key function to the values
        before sorting. This is similar to the `key` argument in the
        builtin :meth:`sorted` function, with the notable difference that
        this `key` function should be *vectorized*. It should expect a
        ``Series`` and return a Series with the same shape as the input.
        It will be applied to each column in `by` independently. The values in the
        returned Series will be used as the keys for sorting.

    Returns
    -------
    DataFrame or None
        DataFrame with sorted values or None if ``inplace=True``.

    See Also
    --------
    DataFrame.sort_index : Sort a DataFrame by the index.
    Series.sort_values : Similar method for a Series.

    Examples
    --------
    >>> df = pd.DataFrame(
    ...     {
    ...         "col1": ["A", "A", "B", np.nan, "D", "C"],
    ...         "col2": [2, 1, 9, 8, 7, 4],
    ...         "col3": [0, 1, 9, 4, 2, 3],
    ...         "col4": ["a", "B", "c", "D", "e", "F"],
    ...     }
    ... )
    >>> df
      col1  col2  col3 col4
    0    A     2     0    a
    1    A     1     1    B
    2    B     9     9    c
    3  NaN     8     4    D
    4    D     7     2    e
    5    C     4     3    F

    **Sort by a single column**

    In this case, we are sorting the rows according to values in ``col1``:

    >>> df.sort_values(by=["col1"])
      col1  col2  col3 col4
    0    A     2     0    a
    1    A     1     1    B
    2    B     9     9    c
    5    C     4     3    F
    4    D     7     2    e
    3  NaN     8     4    D

    **Sort by multiple columns**

    You can also provide multiple columns to ``by`` argument, as shown below.
    In this example, the rows are first sorted according to ``col1``, and then
    the rows that have an identical value in ``col1`` are sorted according
    to ``col2``.

    >>> df.sort_values(by=["col1", "col2"])
      col1  col2  col3 col4
    1    A     1     1    B
    0    A     2     0    a
    2    B     9     9    c
    5    C     4     3    F
    4    D     7     2    e
    3  NaN     8     4    D

    **Sort in a descending order**

    The sort order can be reversed using ``ascending`` argument, as shown below:

    >>> df.sort_values(by="col1", ascending=False)
      col1  col2  col3 col4
    4    D     7     2    e
    5    C     4     3    F
    2    B     9     9    c
    0    A     2     0    a
    1    A     1     1    B
    3  NaN     8     4    D

    **Placing any** ``NA`` **first**

    Note that in the above example, the rows that contain an ``NA`` value in their
    ``col1`` are placed at the end of the dataframe. This behavior can be modified
    via ``na_position`` argument, as shown below:

    >>> df.sort_values(by="col1", ascending=False, na_position="first")
      col1  col2  col3 col4
    3  NaN     8     4    D
    4    D     7     2    e
    5    C     4     3    F
    2    B     9     9    c
    0    A     2     0    a
    1    A     1     1    B

    **Customized sort order**

    The ``key`` argument allows for a further customization of sorting behaviour.
    For example, you may want
    to ignore the `letter's case <https://en.wikipedia.org/wiki/Letter_case>`__
    when sorting strings:

    >>> df.sort_values(by="col4", key=lambda col: col.str.lower())
       col1  col2  col3 col4
    0    A     2     0    a
    1    A     1     1    B
    2    B     9     9    c
    3  NaN     8     4    D
    4    D     7     2    e
    5    C     4     3    F

    Another typical example is
    `natural sorting <https://en.wikipedia.org/wiki/Natural_sort_order>`__.
    This can be done using
    ``natsort`` `package <https://github.com/SethMMorton/natsort>`__,
    which provides a function to generate a key
    to sort data in their natural order:

    >>> df = pd.DataFrame(
    ...     {
    ...         "hours": ["0hr", "128hr", "0hr", "64hr", "64hr", "128hr"],
    ...         "mins": [
    ...             "10mins",
    ...             "40mins",
    ...             "40mins",
    ...             "40mins",
    ...             "10mins",
    ...             "10mins",
    ...         ],
    ...         "value": [10, 20, 30, 40, 50, 60],
    ...     }
    ... )
    >>> df
       hours    mins  value
    0    0hr  10mins     10
    1  128hr  40mins     20
    2    0hr  40mins     30
    3   64hr  40mins     40
    4   64hr  10mins     50
    5  128hr  10mins     60
    >>> from natsort import natsort_keygen
    >>> df.sort_values(
    ...     by=["hours", "mins"],
    ...     key=natsort_keygen(),
    ... )
       hours    mins  value
    0    0hr  10mins     10
    2    0hr  40mins     30
    4   64hr  10mins     50
    3   64hr  40mins     40
    5  128hr  10mins     60
    1  128hr  40mins     20

In [68]:
orders.sort_values('order_customer_id', ascending=False)

       order_id             order_date  order_customer_id     order_status
41642     41643  2014-04-08 00:00:00.0              12435          PENDING
61628     61629  2013-12-21 00:00:00.0              12435         CANCELED
4798       4799  2013-08-23 00:00:00.0              12434  PENDING_PAYMENT
5302       5303  2013-08-26 00:00:00.0              12434          PENDING
1867       1868  2013-08-03 00:00:00.0              12434           CLOSED
...         ...                    ...                ...              ...
67862     67863  2013-11-30 00:00:00.0                  2         COMPLETE
33864     33865  2014-02-18 00:00:00.0                  2         COMPLETE
15191     15192  2013-10-29 00:00:00.0                  2  PENDING_PAYMENT
57962     57963  2013-08-02 00:00:00.0                  2          ON_HOLD
22944     22945  2013-12-13 00:00:00.0                  1         COMPLETE

[68883 rows x 4 columns]

In [69]:
orders.sort_values(['order_customer_id', 'order_date'])

       order_id             order_date  order_customer_id     order_status
22944     22945  2013-12-13 00:00:00.0                  1         COMPLETE
57962     57963  2013-08-02 00:00:00.0                  2          ON_HOLD
15191     15192  2013-10-29 00:00:00.0                  2  PENDING_PAYMENT
67862     67863  2013-11-30 00:00:00.0                  2         COMPLETE
33864     33865  2014-02-18 00:00:00.0                  2         COMPLETE
...         ...                    ...                ...              ...
61776     61777  2013-12-26 00:00:00.0              12434         COMPLETE
42914     42915  2014-04-16 00:00:00.0              12434         COMPLETE
51799     51800  2014-06-14 00:00:00.0              12434          ON_HOLD
61628     61629  2013-12-21 00:00:00.0              12435         CANCELED
41642     41643  2014-04-08 00:00:00.0              12435          PENDING

[68883 rows x 4 columns]

In [70]:
orders.sort_values(
    ['order_customer_id', 'order_date'],
    ascending=[False, True])

       order_id             order_date  order_customer_id     order_status
61628     61629  2013-12-21 00:00:00.0              12435         CANCELED
41642     41643  2014-04-08 00:00:00.0              12435          PENDING
1867       1868  2013-08-03 00:00:00.0              12434           CLOSED
4798       4799  2013-08-23 00:00:00.0              12434  PENDING_PAYMENT
5302       5303  2013-08-26 00:00:00.0              12434          PENDING
...         ...                    ...                ...              ...
57962     57963  2013-08-02 00:00:00.0                  2          ON_HOLD
15191     15192  2013-10-29 00:00:00.0                  2  PENDING_PAYMENT
67862     67863  2013-11-30 00:00:00.0                  2         COMPLETE
33864     33865  2014-02-18 00:00:00.0                  2         COMPLETE
22944     22945  2013-12-13 00:00:00.0                  1         COMPLETE

[68883 rows x 4 columns]

In [71]:
orders.to_csv?

Signature:
orders.to_csv(
    path_or_buf: 'FilePath | WriteBuffer[bytes] | WriteBuffer[str] | None' = None,
    *,
    sep: 'str' = ',',
    na_rep: 'str' = '',
    float_format: 'str | Callable | None' = None,
    columns: 'Sequence[Hashable] | None' = None,
    header: 'bool | list[str]' = True,
    index: 'bool' = True,
    index_label: 'IndexLabel | None' = None,
    mode: 'str' = 'w',
    encoding: 'str | None' = None,
    compression: 'CompressionOptions' = 'infer',
    quoting: 'int | None' = None,
    quotechar: 'str' = '"',
    lineterminator: 'str | None' = None,
    chunksize: 'int | None' = None,
    date_format: 'str | None' = None,
    doublequote: 'bool' = True,
    escapechar: 'str | None' = None,
    decimal: 'str' = '.',
    errors: 'OpenFileErrors' = 'strict',
    storage_options: 'StorageOptions | None' = None,
) -> 'str | None'
Docstring:
Write object to a comma-separated values (csv) file.

Parameters
----------
path_or_buf : str, path object, file-like object, or None, default None
    String, path object (implementing os.PathLike[str]), or file-like
    object implementing a write() function. If None, the result is
    returned as a string. If a non-binary file object is passed, it should
    be opened with `newline=''`, disabling universal newlines. If a binary
    file object is passed, `mode` might need to contain a `'b'`.
sep : str, default ','
    String of length 1. Field delimiter for the output file.
na_rep : str, default ''
    Missing data representation.
float_format : str, Callable, default None
    Format string for floating point numbers. If a Callable is given, it takes
    precedence over other numeric formatting parameters, like decimal.
columns : sequence, optional
    Columns to write.
header : bool or list of str, default True
    Write out the column names. If a list of strings is given it is
    assumed to be aliases for the column names.
index : bool, default True
    Write row names (index).
index_label : str or sequence, or False, default None
    Column label for index column(s) if desired. If None is given, and
    `header` and `index` are True, then the index names are used. A
    sequence should be given if the object uses MultiIndex. If
    False do not print fields for index names. Use index_label=False
    for easier importing in R.
mode : {{'w', 'x', 'a'}}, default 'w'
    Forwarded to either `open(mode=)` or `fsspec.open(mode=)` to control
    the file opening. Typical values include:

    - 'w', truncate the file first.
    - 'x', exclusive creation, failing if the file already exists.
    - 'a', append to the end of file if it exists.

encoding : str, optional
    A string representing the encoding to use in the output file,
    defaults to 'utf-8'. `encoding` is not supported if `path_or_buf`
    is a non-binary file object.

compression : str or dict, default 'infer'
    For on-the-fly compression of the output data. If 'infer' and
    'path_or_buf' is path-like, then detect compression from the following
    extensions: '.gz',
    '.bz2', '.zip', '.xz', '.zst', '.tar', '.tar.gz', '.tar.xz' or '.tar.bz2'
    (otherwise no compression).
    Set to ``None`` for no compression.
    Can also be a dict with key ``'method'`` set to one of
    {``'zip'``, ``'gzip'``, ``'bz2'``, ``'zstd'``, ``'xz'``, ``'tar'``} and
    other key-value pairs are forwarded to
    ``zipfile.ZipFile``, ``gzip.GzipFile``,
    ``bz2.BZ2File``, ``zstandard.ZstdCompressor``, ``lzma.LZMAFile`` or
    ``tarfile.TarFile``, respectively.
    As an example, the following could be passed for faster compression and
    to create a reproducible gzip archive:
    ``compression={'method': 'gzip', 'compresslevel': 1, 'mtime': 1}``.

       May be a dict with key 'method' as compression mode
       and other entries as additional compression options if
       compression mode is 'zip'.

       Passing compression options as keys in dict is
       supported for compression modes 'gzip', 'bz2', 'zstd', and 'zip'.
quoting : optional constant from csv module
    Defaults to csv.QUOTE_MINIMAL. If you have set a `float_format`
    then floats are converted to strings and thus csv.QUOTE_NONNUMERIC
    will treat them as non-numeric.
quotechar : str, default '\"'
    String of length 1. Character used to quote fields.
lineterminator : str, optional
    The newline character or character sequence to use in the output
    file. Defaults to `os.linesep`, which depends on the OS in which
    this method is called ('\\n' for linux, '\\r\\n' for Windows, i.e.).
chunksize : int or None
    Rows to write at a time.
date_format : str, default None
    Format string for datetime objects.
doublequote : bool, default True
    Control quoting of `quotechar` inside a field.
escapechar : str, default None
    String of length 1. Character used to escape `sep` and `quotechar`
    when appropriate.
decimal : str, default '.'
    Character recognized as decimal separator. E.g. use ',' for
    European data.
errors : str, default 'strict'
    Specifies how encoding and decoding errors are to be handled.
    See the errors argument for :func:`open` for a full list
    of options.

storage_options : dict, optional
    Extra options that make sense for a particular storage connection, e.g.
    host, port, username, password, etc. For HTTP(S) URLs the key-value pairs
    are forwarded to ``urllib.request.Request`` as header options. For other
    URLs (e.g. starting with "s3://", and "gcs://") the key-value pairs are
    forwarded to ``fsspec.open``. Please see ``fsspec`` and ``urllib`` for more
    details, and for more examples on storage options refer `here
    <https://pandas.pydata.org/docs/user_guide/io.html?
    highlight=storage_options#reading-writing-remote-files>`_.

Returns
-------
None or str
    If path_or_buf is None, returns the resulting csv format as a
    string. Otherwise returns None.

See Also
--------
read_csv : Load a CSV file into a DataFrame.
to_excel : Write DataFrame to an Excel file.

Examples
--------
Create 'out.csv' containing 'df' without indices

>>> df = pd.DataFrame(
...     [["Raphael", "red", "sai"], ["Donatello", "purple", "bo staff"]],
...     columns=["name", "mask", "weapon"],
... )
>>> df.to_csv("out.csv", index=False)  # doctest: +SKIP

Create 'out.zip' containing 'out.csv'

>>> df.to_csv(index=False)
'name,mask,weapon\nRaphael,red,sai\nDonatello,purple,bo staff\n'
>>> compression_opts = dict(
...     method="zip", archive_name="out.csv"
... )  # doctest: +SKIP
>>> df.to_csv(
...     "out.zip", index=False, compression=compression_opts
... )  # doctest: +SKIP

To write a csv file to a new folder or nested folder you will first
need to create it using either Pathlib or os:

>>> from pathlib import Path  # doctest: +SKIP
>>> filepath = Path("folder/subfolder/out.csv")  # doctest: +SKIP
>>> filepath.parent.mkdir(parents=True, exist_ok=True)  # doctest: +SKIP
>>> df.to_csv(filepath)  # doctest: +SKIP

>>> import os  # doctest: +SKIP
>>> os.makedirs("folder/subfolder", exist_ok=True)  # doctest: +SKIP
>>> df.to_csv("folder/subfolder/out.csv")  # doctest: +SKIP

Format floats to two decimal places:

>>> df.to_csv("out1.csv", float_format="%.2f")  # doctest: +SKIP

Format floats using scientific notation:

>>> df.to_csv("out2.csv", float_format="{{:.2e}}".format)  # doctest: +SKIP
File:      /opt/miniconda3/lib/python3.13/site-packages/pandas/core/generic.py
Type:      method

In [73]:
import os

os.makedirs('/Users/franciscocoelho/VSCodeProjects/franciscocoelh0/Random_Scripts/data/retail_db/orders_json', exist_ok=True)

In [75]:
# Save data using columnar format
orders.to_json('/Users/franciscocoelho/VSCodeProjects/franciscocoelh0/Random_Scripts/data/retail_db/orders_json/part-00000')

In [76]:
# Save data using row format
orders.to_json('/Users/franciscocoelho/VSCodeProjects/franciscocoelh0/Random_Scripts/data/retail_db/orders_json/part-00000',
                orient='records',
                  lines=True
                  )

In [78]:
pd.read_json('/Users/franciscocoelho/VSCodeProjects/franciscocoelh0/Random_Scripts/data/retail_db/orders_json/part-00000',lines=True)

       order_id             order_date  order_customer_id     order_status
0             1  2013-07-25 00:00:00.0              11599           CLOSED
1             2  2013-07-25 00:00:00.0                256  PENDING_PAYMENT
2             3  2013-07-25 00:00:00.0              12111         COMPLETE
3             4  2013-07-25 00:00:00.0               8827           CLOSED
4             5  2013-07-25 00:00:00.0              11318         COMPLETE
...         ...                    ...                ...              ...
68878     68879  2014-07-09 00:00:00.0                778         COMPLETE
68879     68880  2014-07-13 00:00:00.0               1117         COMPLETE
68880     68881  2014-07-19 00:00:00.0               2518  PENDING_PAYMENT
68881     68882  2014-07-22 00:00:00.0              10000          ON_HOLD
68882     68883  2014-07-23 00:00:00.0               5533         COMPLETE

[68883 rows x 4 columns]