In [4]:
%load_ext sql

In [2]:
import os
os.environ.get("DBHOST")

In [5]:
%env DATABASE_URL=postgresql://itversity_retail_user:itversity@localhost:5432/itversity_retail_db

env: DATABASE_URL=postgresql://itversity_retail_user:itversity@localhost:5432/itversity_retail_db

In [6]:
%env DATABASE_URL

'postgresql://itversity_retail_user:itversity@localhost:5432/itversity_retail_db'

In [3]:
%env DB_HOST=localhost

env: DB_HOST=localhost

In [8]:
%%sql

select * FROM orders LIMIT 10;

10 rows affected.

[(1, datetime.datetime(2013, 7, 25, 0, 0), 11599, 'CLOSED'),
 (2, datetime.datetime(2013, 7, 25, 0, 0), 256, 'PENDING_PAYMENT'),
 (3, datetime.datetime(2013, 7, 25, 0, 0), 12111, 'COMPLETE'),
 (4, datetime.datetime(2013, 7, 25, 0, 0), 8827, 'CLOSED'),
 (5, datetime.datetime(2013, 7, 25, 0, 0), 11318, 'COMPLETE'),
 (6, datetime.datetime(2013, 7, 25, 0, 0), 7130, 'COMPLETE'),
 (7, datetime.datetime(2013, 7, 25, 0, 0), 4530, 'COMPLETE'),
 (8, datetime.datetime(2013, 7, 25, 0, 0), 2911, 'PROCESSING'),
 (9, datetime.datetime(2013, 7, 25, 0, 0), 5657, 'PENDING_PAYMENT'),
 (10, datetime.datetime(2013, 7, 25, 0, 0), 5648, 'PENDING_PAYMENT')]

In [9]:
import pandas as pd

In [10]:
help(pd.read_sql)

Help on function read_sql in module pandas:

read_sql(
    sql,
    con,
    index_col: 'str | list[str] | None' = None,
    coerce_float: 'bool' = True,
    params=None,
    parse_dates=None,
    columns: 'list[str] | None' = None,
    chunksize: 'int | None' = None,
    dtype_backend: 'DtypeBackend | lib.NoDefault' = <no_default>,
    dtype: 'DtypeArg | None' = None
) -> 'DataFrame | Iterator[DataFrame]'
    Read SQL query or database table into a DataFrame.

    This function is a convenience wrapper around ``read_sql_table`` and
    ``read_sql_query`` (for backward compatibility). It will delegate
    to the specific function depending on the provided input. A SQL query
    will be routed to ``read_sql_query``, while a database table name will
    be routed to ``read_sql_table``. Note that the delegated function might
    have more specific notes about their functionality not listed here.

    Parameters
    ----------
    sql : str or SQLAlchemy Selectable (select or text object)
        SQL query to be executed or a table name.
    con : ADBC Connection, SQLAlchemy connectable, str, or sqlite3 connection
        ADBC provides high performance I/O with native type support, where available.
        Using SQLAlchemy makes it possible to use any DB supported by that
        library. If a DBAPI2 object, only sqlite3 is supported. The user is responsible
        for engine disposal and connection closure for the ADBC connection and
        SQLAlchemy connectable; str connections are closed automatically. See
        `here <https://docs.sqlalchemy.org/en/20/core/connections.html>`_.
    index_col : str or list of str, optional, default: None
        Column(s) to set as index(MultiIndex).
    coerce_float : bool, default True
        Attempts to convert values of non-string, non-numeric objects (like
        decimal.Decimal) to floating point, useful for SQL result sets.
    params : list, tuple or dict, optional, default: None
        List of parameters to pass to execute method.  The syntax used
        to pass parameters is database driver dependent. Check your
        database driver documentation for which of the five syntax styles,
        described in PEP 249's paramstyle, is supported.
        Eg. for psycopg2, uses %(name)s so use params={'name' : 'value'}.
    parse_dates : list or dict, default: None
        - List of column names to parse as dates.
        - Dict of ``{column_name: format string}`` where format string is
          strftime compatible in case of parsing string times, or is one of
          (D, s, ns, ms, us) in case of parsing integer timestamps.
        - Dict of ``{column_name: arg dict}``, where the arg dict corresponds
          to the keyword arguments of :func:`pandas.to_datetime`
          Especially useful with databases without native Datetime support,
          such as SQLite.
    columns : list, default: None
        List of column names to select from SQL table (only used when reading
        a table).
    chunksize : int, default None
        If specified, return an iterator where `chunksize` is the
        number of rows to include in each chunk.
    dtype_backend : {'numpy_nullable', 'pyarrow'}
        Back-end data type applied to the resultant :class:`DataFrame`
        (still experimental). If not specified, the default behavior
        is to not use nullable data types. If specified, the behavior
        is as follows:

        * ``"numpy_nullable"``: returns nullable-dtype-backed :class:`DataFrame`
        * ``"pyarrow"``: returns pyarrow-backed nullable
          :class:`ArrowDtype` :class:`DataFrame`

        .. versionadded:: 2.0
    dtype : Type name or dict of columns
        Data type for data or columns. E.g. np.float64 or
        {'a': np.float64, 'b': np.int32, 'c': 'Int64'}.
        The argument is ignored if a table is passed instead of a query.

        .. versionadded:: 2.0.0

    Returns
    -------
    DataFrame or Iterator[DataFrame]
        Returns a DataFrame object that contains the result set of the
        executed SQL query or an SQL Table based on the provided input,
        in relation to the specified database connection.

    See Also
    --------
    read_sql_table : Read SQL database table into a DataFrame.
    read_sql_query : Read SQL query into a DataFrame.

    Notes
    -----
    ``pandas`` does not attempt to sanitize SQL statements;
    instead it simply forwards the statement you are executing
    to the underlying driver, which may or may not sanitize from there.
    Please refer to the underlying driver documentation for any details.
    Generally, be wary when accepting statements from arbitrary sources.

    Examples
    --------
    Read data from SQL via either a SQL query or a SQL tablename.
    When using a SQLite database only SQL queries are accepted,
    providing only the SQL tablename will result in an error.

    >>> from sqlite3 import connect
    >>> conn = connect(":memory:")
    >>> df = pd.DataFrame(
    ...     data=[[0, "10/11/12"], [1, "12/11/10"]],
    ...     columns=["int_column", "date_column"],
    ... )
    >>> df.to_sql(name="test_data", con=conn)
    2

    >>> pd.read_sql("SELECT int_column, date_column FROM test_data", conn)
       int_column date_column
    0           0    10/11/12
    1           1    12/11/10

    >>> pd.read_sql("test_data", "postgres:///db_name")  # doctest:+SKIP

    For parameterized query, using ``params`` is recommended over string interpolation.

    >>> from sqlalchemy import text
    >>> sql = text(
    ...     "SELECT int_column, date_column FROM test_data WHERE int_column=:int_val"
    ... )
    >>> pd.read_sql(sql, conn, params={"int_val": 1})  # doctest:+SKIP
       int_column date_column
    0           1    12/11/10

    Apply date parsing to columns through the ``parse_dates`` argument
    The ``parse_dates`` argument calls ``pd.to_datetime`` on the provided columns.
    Custom argument values for applying ``pd.to_datetime`` on a column are specified
    via a dictionary format:

    >>> pd.read_sql(
    ...     "SELECT int_column, date_column FROM test_data",
    ...     conn,
    ...     parse_dates={"date_column": {"format": "%d/%m/%y"}},
    ... )
       int_column date_column
    0           0  2012-11-10
    1           1  2010-11-12

    .. versionadded:: 2.2.0

       pandas now supports reading via ADBC drivers

    >>> from adbc_driver_postgresql import dbapi  # doctest:+SKIP
    >>> with dbapi.connect("postgres:///db_name") as conn:  # doctest:+SKIP
    ...     pd.read_sql("SELECT int_column FROM test_data", conn)
       int_column
    0           0
    1           1

In [15]:
conn_uri = 'postgresql://itversity_retail_user:itversity@localhost:5432/itversity_retail_db'

In [ ]:
pd.read_sql('orders', conn_uri)

       order_id order_date  order_customer_id     order_status
0             1 2013-07-25              11599           CLOSED
1             2 2013-07-25                256  PENDING_PAYMENT
2             3 2013-07-25              12111         COMPLETE
3             4 2013-07-25               8827           CLOSED
4             5 2013-07-25              11318         COMPLETE
...         ...        ...                ...              ...
68878     68879 2014-07-09                778         COMPLETE
68879     68880 2014-07-13               1117         COMPLETE
68880     68881 2014-07-19               2518  PENDING_PAYMENT
68881     68882 2014-07-22              10000          ON_HOLD
68882     68883 2014-07-23               5533         COMPLETE

[68883 rows x 4 columns]

In [17]:
query = '''SELECT * FROM orders LIMIT 10'''

In [18]:
pd.read_sql(query, conn_uri)

   order_id order_date  order_customer_id     order_status
0         1 2013-07-25              11599           CLOSED
1         2 2013-07-25                256  PENDING_PAYMENT
2         3 2013-07-25              12111         COMPLETE
3         4 2013-07-25               8827           CLOSED
4         5 2013-07-25              11318         COMPLETE
5         6 2013-07-25               7130         COMPLETE
6         7 2013-07-25               4530         COMPLETE
7         8 2013-07-25               2911       PROCESSING
8         9 2013-07-25               5657  PENDING_PAYMENT
9        10 2013-07-25               5648  PENDING_PAYMENT

In [55]:
%%sql

DROP TABLE IF EXISTS orders CASCADE

 * postgresql://itversity_retail_user:***@localhost:5432/itversity_retail_db
Done.

[]

In [36]:
pd.read_sql(query, conn_uri)

Empty DataFrame
Columns: [order_id, order_date, order_customer_id, order_status]
Index: []

In [37]:
import pandas as pd

In [60]:
# Get the metada (column names)
def get_column_names(schemas, ds_name, sorting_key='column_position'):
    column_details = schemas[ds_name]
    columns = sorted(column_details, key=lambda col: col[sorting_key])
    return [col['column_name'] for col in columns]

In [39]:
import json

In [40]:
schemas = json.load(open('retail_db/schemas.json'))

In [41]:
columns = get_column_names(schemas, 'orders')

In [66]:
ds_name = 'orders'

In [76]:
df_reader = pd.read_csv(f'retail_db/{ds_name}/part-00000', names=columns, chunksize=10000)

In [81]:
df_reader

In [77]:
type(df)

pandas.io.parsers.readers.TextFileReader

In [78]:
df_list = list(df_reader)

In [80]:
df_list[1]

       order_id             order_date  order_customer_id     order_status
10000     10001  2013-09-25 00:00:00.0                316  PENDING_PAYMENT
10001     10002  2013-09-25 00:00:00.0               1530         COMPLETE
10002     10003  2013-09-25 00:00:00.0               8099         COMPLETE
10003     10004  2013-09-25 00:00:00.0               7768           CLOSED
10004     10005  2013-09-25 00:00:00.0                541         COMPLETE
...         ...                    ...                ...              ...
19995     19996  2013-11-25 00:00:00.0              11161  PENDING_PAYMENT
19996     19997  2013-11-25 00:00:00.0               1920         COMPLETE
19997     19998  2013-11-25 00:00:00.0              11672       PROCESSING
19998     19999  2013-11-25 00:00:00.0              10014         COMPLETE
19999     20000  2013-11-25 00:00:00.0                974  PENDING_PAYMENT

[10000 rows x 4 columns]

In [79]:
df_list[-1]

       order_id             order_date  order_customer_id     order_status
60000     60001  2013-10-20 00:00:00.0               1376         COMPLETE
60001     60002  2013-10-20 00:00:00.0               6345  PENDING_PAYMENT
60002     60003  2013-10-20 00:00:00.0                329       PROCESSING
60003     60004  2013-10-20 00:00:00.0              10907          PENDING
60004     60005  2013-10-20 00:00:00.0               5156         COMPLETE
...         ...                    ...                ...              ...
68878     68879  2014-07-09 00:00:00.0                778         COMPLETE
68879     68880  2014-07-13 00:00:00.0               1117         COMPLETE
68880     68881  2014-07-19 00:00:00.0               2518  PENDING_PAYMENT
68881     68882  2014-07-22 00:00:00.0              10000          ON_HOLD
68882     68883  2014-07-23 00:00:00.0               5533         COMPLETE

[8883 rows x 4 columns]

In [ ]:
for idx, df in enumerate(df_list): # enumerate gives us the index and the value of the list while avoiding to manage counters (idx)
    print(f'Chunk {idx} has {len(df)} rows')

Chunk 0 has 10000 rows
Chunk 1 has 10000 rows
Chunk 2 has 10000 rows
Chunk 3 has 10000 rows
Chunk 4 has 10000 rows
Chunk 5 has 10000 rows
Chunk 6 has 8883 rows

In [83]:
for idx, df in enumerate(df_list):
    print(f'Processing chunck {idx} with size {df.shape[0]} of {ds_name}')
    df.to_sql(
        'orders',
        conn_uri,
        if_exists='append',
        index=False
    )

Processing chunck 0 with size 10000 of orders
Processing chunck 1 with size 10000 of orders
Processing chunck 2 with size 10000 of orders
Processing chunck 3 with size 10000 of orders
Processing chunck 4 with size 10000 of orders
Processing chunck 5 with size 10000 of orders
Processing chunck 6 with size 8883 of orders

In [84]:
pd.read_sql('orders', conn_uri)

        order_id             order_date  order_customer_id     order_status
0              1  2013-07-25 00:00:00.0              11599           CLOSED
1              2  2013-07-25 00:00:00.0                256  PENDING_PAYMENT
2              3  2013-07-25 00:00:00.0              12111         COMPLETE
3              4  2013-07-25 00:00:00.0               8827           CLOSED
4              5  2013-07-25 00:00:00.0              11318         COMPLETE
...          ...                    ...                ...              ...
137761     68879  2014-07-09 00:00:00.0                778         COMPLETE
137762     68880  2014-07-13 00:00:00.0               1117         COMPLETE
137763     68881  2014-07-19 00:00:00.0               2518  PENDING_PAYMENT
137764     68882  2014-07-22 00:00:00.0              10000          ON_HOLD
137765     68883  2014-07-23 00:00:00.0               5533         COMPLETE

[137766 rows x 4 columns]

In [45]:
help(pd.read_sql_query)

Help on function read_sql_query in module pandas:

read_sql_query(
    sql,
    con,
    index_col: 'str | list[str] | None' = None,
    coerce_float: 'bool' = True,
    params: 'list[Any] | Mapping[str, Any] | None' = None,
    parse_dates: 'list[str] | dict[str, str] | dict[str, dict[str, Any]] | None' = None,
    chunksize: 'int | None' = None,
    dtype: 'DtypeArg | None' = None,
    dtype_backend: 'DtypeBackend | lib.NoDefault' = <no_default>
) -> 'DataFrame | Iterator[DataFrame]'
    Read SQL query into a DataFrame.

    Returns a DataFrame corresponding to the result set of the query
    string. Optionally provide an `index_col` parameter to use one of the
    columns as the index, otherwise default integer index will be used.

    Parameters
    ----------
    sql : str SQL query or SQLAlchemy Selectable (select or text object)
        SQL query to be executed.
    con : SQLAlchemy connectable, str, or sqlite3 connection
        Using SQLAlchemy makes it possible to use any DB supported by that
        library. If a DBAPI2 object, only sqlite3 is supported.
    index_col : str or list of str, optional, default: None
        Column(s) to set as index(MultiIndex).
    coerce_float : bool, default True
        Attempts to convert values of non-string, non-numeric objects (like
        decimal.Decimal) to floating point. Useful for SQL result sets.
    params : list, tuple or mapping, optional, default: None
        List of parameters to pass to execute method.  The syntax used
        to pass parameters is database driver dependent. Check your
        database driver documentation for which of the five syntax styles,
        described in PEP 249's paramstyle, is supported.
        Eg. for psycopg2, uses %(name)s so use params={'name' : 'value'}.
    parse_dates : list or dict, default: None
        - List of column names to parse as dates.
        - Dict of ``{column_name: format string}`` where format string is
          strftime compatible in case of parsing string times, or is one of
          (D, s, ns, ms, us) in case of parsing integer timestamps.
        - Dict of ``{column_name: arg dict}``, where the arg dict corresponds
          to the keyword arguments of :func:`pandas.to_datetime`
          Especially useful with databases without native Datetime support,
          such as SQLite.
    chunksize : int, default None
        If specified, return an iterator where `chunksize` is the number of
        rows to include in each chunk.
    dtype : Type name or dict of columns
        Data type for data or columns. E.g. np.float64 or
        {'a': np.float64, 'b': np.int32, 'c': 'Int64'}.
    dtype_backend : {'numpy_nullable', 'pyarrow'}
        Back-end data type applied to the resultant :class:`DataFrame`
        (still experimental). If not specified, the default behavior
        is to not use nullable data types. If specified, the behavior
        is as follows:

        * ``"numpy_nullable"``: returns nullable-dtype-backed :class:`DataFrame`
        * ``"pyarrow"``: returns pyarrow-backed nullable
          :class:`ArrowDtype` :class:`DataFrame`

        .. versionadded:: 2.0

    Returns
    -------
    DataFrame or Iterator[DataFrame]
        Returns a DataFrame object that contains the result set of the
        executed SQL query, in relation to the specified database connection.

    See Also
    --------
    read_sql_table : Read SQL database table into a DataFrame.
    read_sql : Read SQL query or database table into a DataFrame.

    Notes
    -----
    Any datetime values with time zone information parsed via the `parse_dates`
    parameter will be converted to UTC.

    Examples
    --------
    >>> from sqlalchemy import create_engine  # doctest: +SKIP
    >>> engine = create_engine("sqlite:///database.db")  # doctest: +SKIP
    >>> sql_query = "SELECT int_column FROM test_data"  # doctest: +SKIP
    >>> with engine.connect() as conn, conn.begin():  # doctest: +SKIP
    ...     data = pd.read_sql_query(sql_query, conn)  # doctest: +SKIP

In [56]:
df.to_sql('orders', conn_uri, if_exists='replace', index=False)

883

In [ ]:
pd.read_sql('orders', conn_uri)